In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC

In [2]:
data=pd.read_csv('clean_bmart.csv',sep=',')
data.head()

Unnamed: 0 Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           0           FDA15         9.30          Low Fat         0.016047   
1           1           DRC01         5.92          Regular         0.019278   
2           2           FDN15        17.50          Low Fat         0.016760   
3           3           FDX07        19.20          Regular         0.000000   
4           4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998      Medium               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [4]:
X=data.loc[(data['Outlet_Location_Type']=='Tier 1')|(data['Outlet_Location_Type']=='Tier 2')]

y=X.values[:,10]
x=X.values[:,[4,8]]
ley=LabelEncoder()
ley.fit(y)
y=ley.transform(y)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
print(y)
print(x)
print(data.columns.values[[4,8,10]])

[0 0 1 ... 1 1 0]
[[0.016047301 1999]
 [0.016760075 1999]
 [0.016687114 2002]
 ...
 [0.046982429000000006 2002]
 [0.035186271 2004]
 [0.04487828 1997]]
['Item_Visibility' 'Outlet_Establishment_Year' 'Outlet_Location_Type']


In [5]:
from sklearn.neural_network import MLPClassifier

In [36]:
mlp=MLPClassifier(hidden_layer_sizes=(5),max_iter=1000,random_state=0)

In [37]:
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=5, learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=0, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [38]:
predictions=mlp.predict(X_test)

In [18]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[  0 747]
 [  0 805]]


In [10]:
print('Accuracy: %.2f' % accuracy_score(y_test, predictions))

Accuracy: 0.52


In [11]:
model=SVC(kernel='linear',C=1)
model.fit(X_train,y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
predictions=model.predict(X_test)

In [13]:
print('Accuracy: %.2f' % accuracy_score(y_test, predictions))

Accuracy: 1.00


In [14]:
print(confusion_matrix(y_test,predictions))

[[747   0]
 [  0 805]]
